library(dplyr)
library(data.table)
library(tibble)
library(ComplexHeatmap)
library(EnrichedHeatmap)
library(circlize)
library(ggplot2)
require(doParallel)
library(amap)
library(imputeTS)
library(lazyeval)
require(XLConnect)
options(java.parameters = "- Xmx4g")
xlcFreeMemory()


rm(list = ls())

source(file = "E:/Chris_UM/Codes/ChIP_seq/TF_polII_functions.R")


path = "E:/Chris_UM/Analysis/21_CL2017_ChIPmix_ULAS_MIX/ULAS_AN"
setwd(path)

## 1) This script takes the profile matrix *.gz file generated by deeptools
## 2) Generate a profile heatmap and cluster the genes by k-means or hierarchical clustering
## 3) It also reads a pol-II expression matrix and plot these expression values as heatmap

##################################################################################

TF_profile = "An_laeA_48h_HA"
polII_sample = "An_untagged_48h_polII"
name = "An_laeA_48h_HA"
clusters = 7

smGenes_file = "AN_SM_genes.tab"



TF_dataPath = paste0("TF_data/", TF_profile, collapse = "")
polII_dataPath = paste0("polII_data/", polII_sample, collapse = "")

matFile = paste0(TF_dataPath, "/", TF_profile, "_normalized_profile.tab.gz", collapse = "")
polII_file = paste0(polII_dataPath, "/", polII_sample, "_polii_expr.tab.rel.mat", collapse = "")
peakFile = paste0(TF_dataPath, "/", TF_profile, "_peaks_nearest_TSS.tab", collapse = "")

outPrefix_all = paste0(TF_dataPath, "/", name, "_allGenes", collapse = "")
outPrefix_expressed = paste0(TF_dataPath, "/", name, "_expressedGenes", collapse = "")
outPrefix_sm = paste0(TF_dataPath, "/", name, "_SM_genes", collapse = "")
outPrefix_peaks = paste0(TF_dataPath, "/", name, "_peaksGenes", collapse = "")

excelOut <- paste0(outPrefix_all, "_clusters.xlsx", collapse = "")


##################################################################################
## draw heatmap with all the genes


## read the profile matrix
mat1 = getDeeptoolsProfileMatrix(file = matFile, colNames = header, signalName = name)

## check the distribution in data
quantile(mat1, c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 1), na.rm = T)
col_fun = colorRamp2(quantile(mat1, c(0.50, 0.99), na.rm = T), c("white", "red"))


## get first primary profile heatmap
profile1 = primaryProfileHeatmap(profileMat = mat1, signalName = name, numClust = clusters, color = col_fun)


## read polII expression data
expression1 = get_secondary_polII_data(file = polII_file, title = name, clusterData = profile1$cluster)

## add SM cluster information to clusterData
clusterData = add_SM_cluster_info(file = smGenes_file, clusterDf = expression1$clusterDf)

## add macs2 peak calling information to clusterData
clusterData = add_macs2Peak_info(file = peakFile, clusterDf = clusterData)

polII_color = colorRamp2(breaks = quantile(expression1$log2_mat, c(0, 0.90, 0.92, 0.94, 0.96, 0.98, 0.99, 0.992, 0.995, 0.999), na.rm = T), colors = c("white", colors_seq9$YlGnBu))


## polII heatmap
polII_ht = polII_heatmap(log2_matrix = expression1$log2_mat, title = "log2(polII_FPKM+1)", color = polII_color)

htlist_allGenes = profile1$rowAnno + profile1$heatmap + polII_ht

## store the clusterData
write.table(clusterData, file = paste0(outPrefix_all, "_", "clusters", clusters, ".tab"), 
            col.names = T, row.names = F, sep = "\t", quote = F)

unlink(excelOut, recursive = FALSE, force = FALSE)
exc <- loadWorkbook(excelOut , create = TRUE)
xlcFreeMemory()
wrkSheet = name
createSheet(exc, name = wrkSheet)
createFreezePane(exc, sheet = wrkSheet, 2, 2)
setMissingValue(object = exc, value = "NA")
writeWorksheet(object = exc, data = clusterData, sheet = wrkSheet, header = T)
setAutoFilter(object = exc, sheet = wrkSheet, reference = aref(topLeft = "A1", dimension = dim(clusterData)))
xlcFreeMemory()
saveWorkbook(exc)


# draw Heatmap and add the annotation name decoration
png(filename = paste0(outPrefix_all, ".png", collapse = ""), width=10000, height=15000, res = 1100)

draw(htlist_allGenes, 
     annotation_legend_list = list(profile1$legend),
     row_sub_title_side = "left",
     gap = unit(c(2, 10), "mm"))

dev.off()

##################################################################################



##################################################################################
## Draw heatmap with only top 10% expressed genes

expressed_title = paste(name, "top 10% expressed polII genes", sep = " ")

## extract top 10% expressed genes from polII data
expressed_genes = get_expressed_polII_genes(clusterData, n = 10, field = name)

expressed_profileMat = mat1[expressed_genes$gene, ]

## get the profile heatmap for the genes which are in top 10% polII expressed genes
expressed_profile = secondaryProfileHeatmap(profileMat = expressed_profileMat, signalName = name, clusterData = expressed_genes, heatmapColor = col_fun, clusterColor = profile1$clusterColor)

## log2(polII_expression) for expressed genes
expressed_l2 = expression1$log2_mat[expressed_genes$gene, name, drop = F]


quantile(expressed_l2, c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 1), na.rm = T)


# exp_polII_color = colorRamp2(breaks = quantile(expressed_l2, seq(0, 0.99, length.out = 9), na.rm = T), colors = c(colors_seq9$YlGnBu))

## expressed genes polII heatmap
exp_polII_color = colorRamp2(breaks = seq(quantile(expressed_l2, 0), quantile(expressed_l2, 0.99), length.out = 9), colors = c(colors_seq9$YlGnBu))

exp_polII_ht = polII_heatmap(log2_matrix = expressed_l2, title = "log2(polII_FPKM+1)", color = exp_polII_color)


expressed_htlist = expressed_profile$rowAnno + expressed_profile$heatmap + exp_polII_ht


# draw Heatmap and add the annotation name decoration
png(filename = paste0(outPrefix_expressed, ".png", collapse = ""), width=10000, height=15000, res = 1100)

draw(expressed_htlist, 
     annotation_legend_list = list(expressed_profile$legend),
     row_sub_title_side = "left",
     gap = unit(c(2, 10), "mm"))

dev.off()

##################################################################################



##################################################################################
## Draw profile heatmap with SM genes

sm_title = paste(name, "SM genes", sep = " ")

sm_genes = clusterData[which(clusterData$is_SM_gene), ]

smGenes_profileMat = mat1[sm_genes$gene, ]

## get the profile heatmap for the SM genes
sm_profile = secondaryProfileHeatmap(profileMat = smGenes_profileMat, signalName = name, clusterData = sm_genes, heatmapColor = col_fun, clusterColor = profile1$clusterColor)

## log2(polII_expression) for expressed genes
smGenes_l2 = expression1$log2_mat[sm_genes$gene, name, drop = F]

quantile(smGenes_l2, c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 1), na.rm = T)


## expressed genes polII heatmap
sm_polII_color = colorRamp2(breaks = seq(quantile(smGenes_l2, 0), quantile(smGenes_l2, 1), length.out = 9), colors = c(colors_seq9$YlGnBu))

sm_polII_ht = polII_heatmap(log2_matrix = smGenes_l2, title = "log2(polII_FPKM+1)", color = sm_polII_color)


sm_htlist = sm_profile$rowAnno + sm_profile$heatmap + sm_polII_ht


# draw Heatmap and add the annotation name decoration
png(filename = paste0(outPrefix_sm, ".png", collapse = ""), width=10000, height=15000, res = 1100)

draw(sm_htlist, 
     annotation_legend_list = list(sm_profile$legend),
     row_sub_title_side = "left",
     gap = unit(c(2, 10), "mm"))

dev.off()

##################################################################################



##################################################################################
## Draw profile heatmap with the genes for which peak was called by macs2



peak_genes = clusterData[which(clusterData$isPeak), ]

peaks_profileMat = mat1[peak_genes$gene, ]

## get the profile heatmap for the genes nearest to peaks
peaks_profile = secondaryProfileHeatmap(profileMat = peaks_profileMat, signalName = name, clusterData = peak_genes, heatmapColor = col_fun, clusterColor = profile1$clusterColor)

## log2(polII_expression) for the genes nearest to peaks
peakGenes_l2 = expression1$log2_mat[peak_genes$gene, name, drop = F]


quantile(peakGenes_l2, c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 1), na.rm = T)


## expressed genes polII heatmap
peakGenes_polII_color = colorRamp2(breaks = seq(quantile(peakGenes_l2, 0), quantile(peakGenes_l2, 0.99), length.out = 9), colors = c(colors_seq9$YlGnBu))

peaks_polII_ht = polII_heatmap(log2_matrix = peakGenes_l2, title = "log2(polII_FPKM+1)", color = peakGenes_polII_color)


peaks_htlist = peaks_profile$rowAnno + peaks_profile$heatmap + peaks_polII_ht



# draw Heatmap and add the annotation name decoration
png(filename = paste0(outPrefix_peaks, ".png", collapse = ""), width=10000, height=15000, res = 1100)

draw(peaks_htlist, 
     annotation_legend_list = list(peaks_profile$legend),
     row_sub_title_side = "left",
     gap = unit(c(2, 10), "mm"))

dev.off()















